Replace VM2 with isolated-vm
vsc-eco/vsc-node pull request #8
Opened 2023-07-15 12:04 UTC by techcoderx

Due to https://github.com/patriksimek/vm2/issues/533, the execution engine will have to be replaced with [isolated-vm](https://github.com/laverdet/isolated-vm).

The replacement package allows for setting a memory limit (in MB). This may be useful to define a "memory limit" on a transaction basis to calculate a max tx fee for contract calls.

Tested working on my node with some contract calls.

2023-10-05 00:04 UTC, vaultec81 commented
@techcoderx Can you pull from master & resolve merge conflicts?

2023-10-05 02:53 UTC, techcoderx commented
Done, please double check to make sure all the latest methods are being passed in correctly.

2023-10-12 03:58 UTC, vaultec81 requested changes
Contract execution stalls and never completes on my end. Doesn't produce an output or any meaningful output

2023-10-12 03:58 UTC, vaultec81 commented on src/services/contractEngine.ts
> +      await compiled.run(context)
Stalls and fails to execute

2023-10-18 03:16 UTC, techcoderx commented
Apologies for the delay. Missed a few commas in the template which was why it did not compile.

2023-11-02 03:57 UTC, vaultec81 approved these changes
LGTM - passes tests

2023-11-02 03:57 UTC, merged